apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{include "tfservingcache.serviceAccountName" .}}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{include "tfservingcache.serviceAccountName" .}}
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs:
      - list
      - watch
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "tfservingcache.serviceAccountName" .}}
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{include "tfservingcache.serviceAccountName" .}}
subjects:
  - kind: ServiceAccount
    name: {{include "tfservingcache.serviceAccountName" .}}
    namespace: {{.Release.Namespace}}
